### ISSUE TITLE
JMap allKeysPArray should return string[]

### ISSUE THREAD

**Issue by mrowrpurr** [CarlosLeyvaAyala/Papyrus-2-Typescript#1]
https://github.com/CarlosLeyvaAyala/Papyrus-2-Typescript/blob/main/conversions/JContainers/JMap.ts#L50

```ts
export const allKeysPArray = (object: number): string => sn.allKeysPArray(object)
```

Should be:

```ts
export const allKeysPArray = (object: number): string[] => sn.allKeysPArray(object)
```

Same is true for JIntMap and JFormMap, they should also return arrays

**Comment by mrowrpurr** [comment]
Related, the PapyrusUtil FilesInFolder and FoldersInFolder functions can return either:
- `string[]`
- `null` (_`null`, not `undefined`_)

They are currently written as:

```ts
export const FoldersInFolder = (directory: string): string[] => sn.FoldersInFolder(directory)
```

And they should be written as:

```ts
export const FoldersInFolder = (directory: string): string[] | null => sn.FoldersInFolder(directory)
```

**Comment by mrowrpurr** [comment]
I don't know which files are automatically generated and which ones aren't so I don't know how to send a PR!

**Comment by CarlosLeyvaAyala** [comment]
> I don't know which files are automatically generated and which ones aren't so I don't know how to send a PR!

Is this `string[] | null` a thing that usually happens or is it an special case?

BTW, in the case of PapyrusUtil, most files are a hybrid of manual edits with automatic ones (thankfully it seems it won't get updated anymore).

That specific function was automatically generated.

**Comment by CarlosLeyvaAyala** [comment]
> Related, the PapyrusUtil FilesInFolder and FoldersInFolder functions can return either:
> 
> * `string[]`
> * `null` (_`null`, not `undefined`_)
> 
> They are currently written as:
> 
> ```ts
> export const FoldersInFolder = (directory: string): string[] => sn.FoldersInFolder(directory)
> ```
> 
> And they should be written as:
> 
> ```ts
> export const FoldersInFolder = (directory: string): string[] | null => sn.FoldersInFolder(directory)
> ```

So, C++ functions **never** return `undefined`; not here, not anywhere. 

Do I get it right?

**Comment by mrowrpurr** [comment]
> So, C++ functions never return undefined; not here, not anywhere.

Not sure. All I know is that I _specifically_ got `null` when the provided directory name didn't exist

**Comment by mrowrpurr** [comment]
As this is not something the tool might be able to determine on its own, I'll close this. It's more related to the specific libraries and less related to the tool you're creating here.
